### ISSUE TITLE
is not a valid backing value for enum "App\Enum\HafasTravelType"

### ISSUE THREAD

**Issue by MrKrisKrisu** [Traewelling/traewelling#764]
Someone is using the api with wrong values and this causes many 500 errors.
I couldn't reproduce the route yet.

```
[2022-03-11 16:54:22] production.ERROR: "IC" is not a valid backing value for enum "App\Enum\HafasTravelType" {"userId":xxxx,"exception":"[object] (ValueError(code: 0): \"IC\" is not a valid backing value for enum \"App\\Enum\\HafasTravelType\" at vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:804)
[stacktrace]
#0 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(804): App\\Enum\\HafasTravelType::from()
#1 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(747): Illuminate\\Database\\Eloquent\\Model->getEnumCastableAttributeValue()
#2 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(1983): Illuminate\\Database\\Eloquent\\Model->castAttribute()
#3 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(452): Illuminate\\Database\\Eloquent\\Model->transformModelValue()
#4 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(431): Illuminate\\Database\\Eloquent\\Model->getAttributeValue()
#5 vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2034): Illuminate\\Database\\Eloquent\\Model->getAttribute()
#6 app/Http/Resources/StatusResource.php(34): Illuminate\\Database\\Eloquent\\Model->__get()
#7 vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): App\\Http\\Resources\\StatusResource->toArray()
#8 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}()
#9 vendor/laravel/framework/src/Illuminate/Collections/Collection.php(717): array_map()
#10 vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(61): Illuminate\\Support\\Collection->map()
#11 vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(101): Illuminate\\Support\\HigherOrderCollectionProxy->__call()
#12 vendor/laravel/framework/src/Illuminate/Http/Resources/Json/JsonResource.php(95): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toArray()
#13 vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(19): Illuminate\\Http\\Resources\\Json\\JsonResource->resolve()
#14 vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(133): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse()
#15 vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(113): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse()
#16 vendor/laravel/framework/src/Illuminate/Routing/Router.php(816): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse()
#17 vendor/laravel/framework/src/Illuminate/Routing/Router.php(803): Illuminate\\Routing\\Router::toResponse()
#18 vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Router->prepareResponse()
#19 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#20 app/Http/Middleware/PrivacyPolicyInterceptionMiddleware.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\PrivacyPolicyInterceptionMiddleware->handle()
#22 app/Http/Middleware/SemiGuest.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\SemiGuest->handle()
#24 app/Http/Middleware/Api/JsonMiddleware.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Api\\JsonMiddleware->handle()
#26 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#28 vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(126): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(62): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#30 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#31 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\\Pipeline\\Pipeline->then()
#33 vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\\Routing\\Router->runRouteWithinStack()
#34 vendor/laravel/framework/src/Illuminate/Routing/Router.php(666): Illuminate\\Routing\\Router->runRoute()
#35 vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\\Routing\\Router->dispatchToRoute()
#36 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#37 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#38 vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#40 vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#42 vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#44 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#46 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#47 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#49 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#50 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#52 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#54 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#56 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#57 public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->handle()
#58 {main}
"}
```

**Comment by MrKrisKrisu** [comment]
It does not depend on API requests.
We still have old values in train_checkins -> category. We should migrate that.

![image](https://user-images.githubusercontent.com/4103693/157904181-c2f828bc-90d9-43cb-ac19-6c4129dcb58c.png)
